### ISSUE TITLE
Missing Jupyter notebook

### ISSUE THREAD

**Issue by eboraks** [tomasonjo/graphs-network-science#1]
Hi Tom, 

In the book on page 81 you mention Jupyter Notebook on the git repo. I can't find a notebook on github project.

**Comment by tomasonjo** [comment]
Hi @eboraks

Thanks for your interest.
The notebooks are not yet available as the chapters are WIP. You can find some examples how to interact with Neo4j from notebooks at: https://github.com/tomasonjo/blogs

I've also used the latest graphdatascience client, which conveniently returns pandas dataframe that can be easily integrated with other tools: https://github.com/tomasonjo/blogs/blob/master/gds_python/gds_python_intro.ipynb

Notebooks for the first couple of chapters should be ready within a month or two. 

Thanks

**Comment by tomasonjo** [comment]
All the notebooks are now part of the repo: Chapter 9 to 12
